force-app/main/default/objects/Account/fields/SOI_Status__c.field-meta.xml
<CustomField>
    <fullName>SOI_Status__c</fullName>
    <defaultValue>&quot;New&quot;</defaultValue>
    <label>SOI_Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unchanged</fullName>
            </value>
            <value>
                <fullName>Edited</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/SOI_ClubName__c.field-meta.xml
<CustomField>
    <fullName>SOI_ClubName__c</fullName>
    <formula>Account.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SOI_ClubName</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SOI_ConsID__c.field-meta.xml
<CustomField>
    <fullName>SOI_ConsID__c</fullName>
    <label>ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SOI_Medical_Expiry__c.field-meta.xml
<CustomField>
    <fullName>SOI_Medical_Expiry__c</fullName>
    <label>Medical Expiry</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SOI_Membership_Card__c.field-meta.xml
<CustomField>
    <fullName>SOI_Membership_Card__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Membership Card</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SOI_Status__c.field-meta.xml
<CustomField>
    <fullName>SOI_Status__c</fullName>
    <defaultValue>&#39;Not changed&#39;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unchanged</fullName>
            </value>
            <value>
                <fullName>Edited</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Athlete.recordType-meta.xml
<RecordType>
    <fullName>Athlete</fullName>
    <active>true</active>
    <label>Athlete</label>
</RecordType>

force-app/main/default/objects/SOI_Sport__c/SOI_Sport__c.object-meta.xml
<CustomObject>
    <label>Sport</label>
    <nameField>
        <label>Sport Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SOI_Sport__c/fields/SOI_Athlete__c.field-meta.xml
<CustomField>
    <fullName>SOI_Athlete__c</fullName>
    <label>Athlete</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.Name</field>
            <operation>equals</operation>
            <value>Athlete</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Sports</relationshipLabel>
    <relationshipName>Sports</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SOI_Sport__c/fields/SOI_Status__c.field-meta.xml
<CustomField>
    <fullName>SOI_Status__c</fullName>
    <defaultValue>&quot;Unchanged&quot;</defaultValue>
    <label>SOI_Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unchanged</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SOI_AthleteList.cls
public with sharing class SOI_AthleteList {

    public List<contactWrapper> athletes{get; set;}

    
    public SOI_AthleteList() {
        List<Contact> oldAthletes = [select AccountId, Account.Name, SOI_ClubName__c, SOI_ConsID__c, 
                                    Name, Birthdate, SOI_Medical_Expiry__c, SOI_Membership_Card__c, 
                                    (select Name from Sports__r), SOI_Status__c from 
                                    Contact where RecordTypeId IN 
                                    (select Id FROM RecordType where Name = 'Athlete')];
        formatAtheletes(oldAthletes);
    }


    private void formatAtheletes(List<Contact> oldAthletes){
        List<contactWrapper> newAthletes = new List<contactWrapper>();
        for(Contact con: oldAthletes){
            contactWrapper newCon = new contactWrapper(con);
             if(con.Sports__r.size() > 0){
                String mySports = '';
                for(Integer i = 0; i < con.Sports__r.size(); i++){
                    String name = con.Sports__r[i].Name;
                    if(i == 0){
                        mySports = name;
                    }else{
                        mySports = mySports+', '+name;
                    }
                }
                newCon.mySports = mySports;   
            }
            if(con.SOI_Status__c == 'Deleted'){
                newCon.actionLabel = 'Undelete';
            }else{
                newCon.actionLabel = 'Delete';
            }
            newAthletes.add(newCon);
        }
        athletes = newAthletes;
    }

    public class contactWrapper
    {
        public Contact con{get; set;}
        public String mySports {get; set;}
        public String actionLabel {get; set;}
        public contactWrapper(Contact c)
        {
            con = c;
        }
    }
    
}