force-app/main/default/objects/Account/fields/SOI_Status__c.field-meta.xml
<CustomField>
    <fullName>SOI_Status__c</fullName>
    <defaultValue>&quot;New&quot;</defaultValue>
    <label>SOI_Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unchanged</fullName>
            </value>
            <value>
                <fullName>Edited</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/SOI_ActionLabel__c.field-meta.xml
<CustomField>
    <fullName>SOI_ActionLabel__c</fullName>
    <formula>IF( SOI_MarkInactive__c, &#39;Inactive&#39;, &#39;Active&#39;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Display status if Contact is active or inactive</inlineHelpText>
    <label>SOI_ActionLabel</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SOI_Certificate__c.field-meta.xml
<CustomField>
    <fullName>SOI_Certificate__c</fullName>
    <label>Safeguarding</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SOI_ClubName__c.field-meta.xml
<CustomField>
    <fullName>SOI_ClubName__c</fullName>
    <formula>Account.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SOI_ClubName</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SOI_ConsID__c.field-meta.xml
<CustomField>
    <fullName>SOI_ConsID__c</fullName>
    <label>ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SOI_Membership_Card__c.field-meta.xml
<CustomField>
    <fullName>SOI_Membership_Card__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Membership Card</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SOI_myRoles__c.field-meta.xml
<CustomField>
    <fullName>SOI_myRoles__c</fullName>
    <label>Roles</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SOI_Status__c.field-meta.xml
<CustomField>
    <fullName>SOI_Status__c</fullName>
    <defaultValue>&#39;Not changed&#39;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unchanged</fullName>
            </value>
            <value>
                <fullName>Edited</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/SOI_VolunteerType__c.field-meta.xml
<CustomField>
    <fullName>SOI_VolunteerType__c</fullName>
    <label>SOI_VolunteerType</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>general</fullName>
            </value>
            <value>
                <fullName>management</fullName>
            </value>
            <value>
                <fullName>coach</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Volunteer.recordType-meta.xml
<RecordType>
    <fullName>Volunteer</fullName>
    <active>true</active>
    <label>Volunteer</label>
</RecordType>

force-app/main/default/objects/SOI_Roles__c/SOI_Roles__c.object-meta.xml
<CustomObject>
    <label>Volunteer_Role</label>
    <nameField>
        <label>Volunteer_Roles Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Volunteer_Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SOI_Roles__c/fields/SOI_Status__c.field-meta.xml
<CustomField>
    <fullName>SOI_Status__c</fullName>
    <defaultValue>&quot;New&quot;</defaultValue>
    <label>SOI_Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unchanged</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SOI_Roles__c/fields/SOI_Volunteer__c.field-meta.xml
<CustomField>
    <fullName>SOI_Volunteer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SOI_Volunteer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Volunteer_Roles</relationshipLabel>
    <relationshipName>Volunteer_Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SOI_VolunteerController.cls
/**
 *   SOI_VolunteerController
 *   Class to handle the actions related to the soi volunteers in the community portal
 *   @ Damien Fleminks
 *   18-08-2019
 */
public with sharing class SOI_VolunteerController {
   
    @AuraEnabled
    public static User getUser(){
        Id userId = UserInfo.getUserId();
        return [select ContactId, Contact.AccountId, Name, Profile.Name from User where Id = :userId limit 1];
    }

    /**
     *  getVolunteers method
     *  Get all the volunteers the user has access to and format the SOI_myRoles__c related list into a single string field
     */
    @AuraEnabled(cacheable=true)
    public static List<Contact> getVolunteers(String volunteerType){
        System.debug(volunteerType);
        List<Contact> newVolunteers = new List<Contact>();
        for(Contact con: [select AccountId, Account.Name, SOI_ClubName__c, SOI_ConsID__c, 
                                    Name, SOI_Membership_Card__c,SOI_Certificate__c,
                                    (select Name,SOI_Status__c from Volunteer_Roles__r where SOI_Status__c != 'Deleted'), SOI_Status__c, SOI_myRoles__c,
                                    SOI_ActionLabel__c from Contact where SOI_VolunteerType__c includes (:volunteerType) and RecordTypeId IN 
                                    (select Id FROM RecordType where Name = 'Volunteer')]){
            String myRoless = '';
            for(Integer i = 0; i < con.Volunteer_Roles__r.size(); i++){
                if(i == 0){
                    myRoless = con.Volunteer_Roles__r[i].Name;
                }
                else{
                    myRoless = myRoless + ', ' + con.Volunteer_Roles__r[i].Name;
                }
            }
            con.SOI_myRoles__c = myRoless;
            newVolunteers.add(con);    
        }
        return newVolunteers;
    }


    /**
     *  updateStatus method
     *  Updates the status of the volunteer record
     */
    @AuraEnabled

    public static void deleteVolunteer(String Id, String status, String AccId){
            Contact con = [select SOI_Status__c from Contact where  Id = :Id and AccountId = :AccId limit 1];
            con.SOI_Status__c = status;
            update con;
    }


}