force-app/main/default/objects/Account/fields/SOI_Status__c.field-meta.xml
<CustomField>
    <fullName>SOI_Status__c</fullName>
    <defaultValue>&quot;New&quot;</defaultValue>
    <label>SOI_Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unchanged</fullName>
            </value>
            <value>
                <fullName>Edited</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/SOI_venueSports__c.field-meta.xml
<CustomField>
    <fullName>SOI_venueSports__c</fullName>
    <label>SOI_venueSports</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Venue.recordType-meta.xml
<RecordType>
    <fullName>Venue</fullName>
    <active>true</active>
    <label>Venue</label>
</RecordType>

force-app/main/default/objects/Contact/fields/SOI_ActionLabel__c.field-meta.xml
<CustomField>
    <fullName>SOI_ActionLabel__c</fullName>
    <formula>IF( SOI_MarkInactive__c, &#39;Inactive&#39;, &#39;Active&#39;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Display status if Contact is active or inactive</inlineHelpText>
    <label>SOI_ActionLabel</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SOI_Status__c.field-meta.xml
<CustomField>
    <fullName>SOI_Status__c</fullName>
    <defaultValue>&#39;Not changed&#39;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unchanged</fullName>
            </value>
            <value>
                <fullName>Edited</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SOI_Venue_timetable__c/SOI_Venue_timetable__c.object-meta.xml
<CustomObject>
    <label>Timetable</label>
    <nameField>
        <label>Sport Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Venue_timetables</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SOI_Venue_timetable__c/fields/SOI_ActionLabel__c.field-meta.xml
<CustomField>
    <fullName>SOI_ActionLabel__c</fullName>
    <formula>IF( TEXT(SOI_Status__c) = &#39;Deleted&#39;, &#39;Undelete&#39;, &#39;Delete&#39;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SOI_ActionLabel</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SOI_Venue_timetable__c/fields/SOI_Club__c.field-meta.xml
<CustomField>
    <fullName>SOI_Club__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SOI_Club</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Venue_timetables</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SOI_Venue_timetable__c/fields/SOI_Status__c.field-meta.xml
<CustomField>
    <fullName>SOI_Status__c</fullName>
    <defaultValue>&quot;New&quot;</defaultValue>
    <label>SOI_Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SOI_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/SOI_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Unchanged</fullName>
    </customValue>
    <customValue>
        <fullName>Edited</fullName>
    </customValue>
    <customValue>
        <fullName>Deleted</fullName>
    </customValue>
    <customValue>
        <fullName>New</fullName>
    </customValue>
    <masterLabel>SOI_Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SOI_VenueController.cls
/**
 *   SOI_VenueController
 *   Class to handle the actions related to the soi venues in the community portal
 *   @ Damien Fleminks 
 *   22-08-2019
 */
public with sharing class SOI_VenueController {
  
  @AuraEnabled
    public static User getUser(){
        Id userId = UserInfo.getUserId();
        return [select ContactId, Contact.AccountId, Name, Profile.Name from User where Id = :userId limit 1];
    }

    /**
     *  getVenues method
     *  Get all the venues the user has access to and format the SOI_venueSports__c related list into a single string field
     */
    @AuraEnabled(cacheable=true)
    public static List<Account> getVenues(){
        List<Account> newVenues= new List<Account>();
        for(Account acc: [select Name, Parent.Name, ShippingCity, SOI_venueSports__c, 
                                    SOI_Status__c, SOI_ActionLabel__c,
                                    (select Name,SOI_Status__c from Venue_timetables__r where SOI_Status__c != 'Deleted') 
                                    from Account where RecordTypeId IN 
                                    (select Id FROM RecordType where Name = 'Venue')]){
            String myTimes = '';
            for(Integer i = 0; i < acc.Venue_timetables__r.size(); i++){
                if(i == 0){
                    myTimes = acc.Venue_timetables__r[i].Name;
                }
                else{
                    myTimes = myTimes + ', ' + acc.Venue_timetables__r[i].Name;
                }
            }
            acc.SOI_venueSports__c = myTimes;
            newVenues.add(acc);    
        }
        return newVenues;
    }

}