force-app/main/default/objects/Contact/fields/SOI_ActionLabel__c.field-meta.xml
<CustomField>
    <fullName>SOI_ActionLabel__c</fullName>
    <formula>IF( SOI_MarkInactive__c, &#39;Inactive&#39;, &#39;Active&#39;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Display status if Contact is active or inactive</inlineHelpText>
    <label>SOI_ActionLabel</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SOI_IsNew__c.field-meta.xml
<CustomField>
    <fullName>SOI_IsNew__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SOI_IsNew</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SOI_Status__c.field-meta.xml
<CustomField>
    <fullName>SOI_Status__c</fullName>
    <defaultValue>&#39;Not changed&#39;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unchanged</fullName>
            </value>
            <value>
                <fullName>Edited</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SOI_Sport__c/SOI_Sport__c.object-meta.xml
<CustomObject>
    <label>Sport</label>
    <nameField>
        <label>Sport Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SOI_Sport__c/fields/SOI_Status__c.field-meta.xml
<CustomField>
    <fullName>SOI_Status__c</fullName>
    <defaultValue>&quot;Unchanged&quot;</defaultValue>
    <label>SOI_Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unchanged</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SOI_Venue__c/SOI_Venue__c.object-meta.xml
<CustomObject>
    <label>SOI_Venue</label>
    <nameField>
        <label>SOI_Venue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SOI_Venues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SOI_Venue__c/fields/SOI_Status__c.field-meta.xml
<CustomField>
    <fullName>SOI_Status__c</fullName>
    <defaultValue>&quot;New&quot;</defaultValue>
    <label>SOI_Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unchanged</fullName>
                <default>true</default>
                <label>Unchanged</label>
            </value>
            <value>
                <fullName>Edited</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SOI_Venue__c/fields/SOI_venueSports__c.field-meta.xml
<CustomField>
    <fullName>SOI_venueSports__c</fullName>
    <label>SOI_venueSports</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SOI_Venue_timetable__c/SOI_Venue_timetable__c.object-meta.xml
<CustomObject>
    <label>Timetable</label>
    <nameField>
        <label>Sport Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Venue_timetables</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SOI_Venue_timetable__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <formula>SOI_Venue__r.SOI_City__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>City</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SOI_Venue_timetable__c/fields/FRI__c.field-meta.xml
<CustomField>
    <fullName>FRI__c</fullName>
    <formula>TEXT(HOUR( friStart__c ))+ &#39;:&#39; + IF(MINUTE( friStart__c )&lt;10, &#39;0&#39; + TEXT(MINUTE( friStart__c )), TEXT(MINUTE( friStart__c )))
+ &#39;-&#39; +
TEXT(HOUR( friEnd__c )) + &#39;:&#39; + IF(MINUTE( friEnd__c )&lt;10, &#39;0&#39; + TEXT(MINUTE( friEnd__c )), TEXT(MINUTE( friEnd__c )))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FRI</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SOI_Venue_timetable__c/fields/MON__c.field-meta.xml
<CustomField>
    <fullName>MON__c</fullName>
    <formula>TEXT(HOUR( monStart__c ))+ &#39;:&#39; + IF(MINUTE( monStart__c )&lt;10, &#39;0&#39; + TEXT(MINUTE( monStart__c )), TEXT(MINUTE( monStart__c )))
+ &#39;-&#39; +
TEXT(HOUR( monEnd__c )) + &#39;:&#39; + IF(MINUTE( monEnd__c )&lt;10, &#39;0&#39; + TEXT(MINUTE( monEnd__c )), TEXT(MINUTE( monEnd__c )))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>MON</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SOI_Venue_timetable__c/fields/SAT__c.field-meta.xml
<CustomField>
    <fullName>SAT__c</fullName>
    <formula>TEXT(HOUR( satStart__c ))+ &#39;:&#39; + IF(MINUTE( satStart__c )&lt;10, &#39;0&#39; + TEXT(MINUTE( satStart__c )), TEXT(MINUTE( satStart__c )))
+ &#39;-&#39; +
TEXT(HOUR( satEnd__c )) + &#39;:&#39; + IF(MINUTE( satEnd__c )&lt;10, &#39;0&#39; + TEXT(MINUTE( satEnd__c )), TEXT(MINUTE( satEnd__c )))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SAT</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SOI_Venue_timetable__c/fields/SOI_ActionLabel__c.field-meta.xml
<CustomField>
    <fullName>SOI_ActionLabel__c</fullName>
    <formula>IF( TEXT(SOI_Status__c) = &#39;Deleted&#39;, &#39;Undelete&#39;, &#39;Delete&#39;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SOI_ActionLabel</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SOI_Venue_timetable__c/fields/SOI_IsNew__c.field-meta.xml
<CustomField>
    <fullName>SOI_IsNew__c</fullName>
    <defaultValue>true</defaultValue>
    <label>SOI_IsNew</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SOI_Venue_timetable__c/fields/SOI_Sport__c.field-meta.xml
<CustomField>
    <fullName>SOI_Sport__c</fullName>
    <label>SOI_Sport</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SOI_Venue_timetable__c/fields/SOI_Status__c.field-meta.xml
<CustomField>
    <fullName>SOI_Status__c</fullName>
    <defaultValue>&quot;New&quot;</defaultValue>
    <label>SOI_Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SOI_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SOI_Venue_timetable__c/fields/SOI_Venue__c.field-meta.xml
<CustomField>
    <fullName>SOI_Venue__c</fullName>
    <label>SOI_Venue</label>
    <referenceTo>SOI_Venue__c</referenceTo>
    <relationshipLabel>Venue_timetables</relationshipLabel>
    <relationshipName>Venue_timetables</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SOI_Venue_timetable__c/fields/Sport_Name__c.field-meta.xml
<CustomField>
    <fullName>Sport_Name__c</fullName>
    <inlineHelpText>Choose a sport the timeline is for</inlineHelpText>
    <label>Sport_Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Basketball</fullName>
            </value>
            <value>
                <fullName>Soccer</fullName>
            </value>
            <value>
                <fullName>Football</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SOI_Venue_timetable__c/fields/SUN__c.field-meta.xml
<CustomField>
    <fullName>SUN__c</fullName>
    <formula>TEXT(HOUR( sunStart__c ))+ &#39;:&#39; + IF(MINUTE( sunStart__c )&lt;10, &#39;0&#39; + TEXT(MINUTE( sunStart__c )), TEXT(MINUTE( sunStart__c )))
+ &#39;-&#39; +
TEXT(HOUR( sunEnd__c )) + &#39;:&#39; + IF(MINUTE( sunEnd__c )&lt;10, &#39;0&#39; + TEXT(MINUTE( sunEnd__c )), TEXT(MINUTE( sunEnd__c )))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SUN</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SOI_Venue_timetable__c/fields/THU__c.field-meta.xml
<CustomField>
    <fullName>THU__c</fullName>
    <formula>TEXT(HOUR( ThuStart__c ))+ &#39;:&#39; + IF(MINUTE( ThuStart__c )&lt;10, &#39;0&#39; + TEXT(MINUTE( ThuStart__c )), TEXT(MINUTE( ThuStart__c )))
+ &#39;-&#39; +
TEXT(HOUR( ThuEnd__c )) + &#39;:&#39; + IF(MINUTE( ThuEnd__c )&lt;10, &#39;0&#39; + TEXT(MINUTE( ThuEnd__c )), TEXT(MINUTE( ThuEnd__c )))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>THU</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SOI_Venue_timetable__c/fields/TUE__c.field-meta.xml
<CustomField>
    <fullName>TUE__c</fullName>
    <formula>TEXT(HOUR( TueStart__c ))+ &#39;:&#39; + IF(MINUTE( TueStart__c )&lt;10, &#39;0&#39; + TEXT(MINUTE( TueStart__c )), TEXT(MINUTE( TueStart__c )))
+ &#39;-&#39; +
TEXT(HOUR( TueEnd__c )) + &#39;:&#39; + IF(MINUTE( TueEnd__c )&lt;10, &#39;0&#39; + TEXT(MINUTE( TueEnd__c )), TEXT(MINUTE( TueEnd__c )))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TUE</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SOI_Venue_timetable__c/fields/Venue_Name__c.field-meta.xml
<CustomField>
    <fullName>Venue_Name__c</fullName>
    <formula>SOI_Venue__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Venue_Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SOI_Venue_timetable__c/fields/WED__c.field-meta.xml
<CustomField>
    <fullName>WED__c</fullName>
    <formula>TEXT(HOUR( wedStart__c ))+ &#39;:&#39; + IF(MINUTE( wedStart__c )&lt;10, &#39;0&#39; + TEXT(MINUTE( wedStart__c )), TEXT(MINUTE( wedStart__c )))
+ &#39;-&#39; +
TEXT(HOUR( wedEnd__c )) + &#39;:&#39; + IF(MINUTE( wedEnd__c )&lt;10, &#39;0&#39; + TEXT(MINUTE( wedEnd__c )), TEXT(MINUTE( wedEnd__c )))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>WED</label>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/SOI_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Unchanged</fullName>
    </customValue>
    <customValue>
        <fullName>Edited</fullName>
    </customValue>
    <customValue>
        <fullName>Deleted</fullName>
    </customValue>
    <customValue>
        <fullName>New</fullName>
    </customValue>
    <masterLabel>SOI_Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SOI_VenueTimetableController.cls
public with sharing class SOI_VenueTimetableController {
   
   
     @AuraEnabled
    public static User getUser(){
        Id userId = UserInfo.getUserId();
        return [select ContactId, Contact.AccountId, Name, Profile.Name from User where Id = :userId limit 1];
    }

    /**
     *  getVenues method
     *  Get all the venues timetables the user has access to and format the SOI_venueSports__c related list into a single string field
     */
    @AuraEnabled(cacheable=true)
    public static List<SOI_Venue_timetable__c> getVenues(){
        List<SOI_Venue_timetable__c> venueTimetables = [select Name, Sport_Name__c, City__c, Venue_Name__c, MON__c, TUE__c, WED__c, THU__c, FRI__c, SAT__c, SUN__c,
                                    SOI_Venue__c, SOI_Status__c, SOI_Sport__c, SOI_ActionLabel__c from SOI_Venue_timetable__c];
        return venueTimetables;
    }


    /**
     *  updateStatus method
     *  Updates the status of the venue timetable record
     */
    @AuraEnabled
    public static void deleteVenue(String Id, String status, String AccId){
            SOI_Venue_timetable__c tim = [select SOI_Status__c, SOI_IsNew__c from SOI_Venue_timetable__c where  Id = :Id limit 1];

            if(tim.SOI_IsNew__c && tim.SOI_Status__c.equals('Deleted')){
               tim.SOI_Status__c = 'New';
                update tim;
            }
            else{
                tim.SOI_Status__c = status;
                update tim;
            }
    }
}